# Generated by Django 5.0.7 on 2024-07-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=60, unique=True)),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
    ]
